name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Xcode environment
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app/Contents/Developer

    - name: Build and Test
      run: xcodebuild test -project ActionsTests.xcodeproj -scheme ActionsTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' -allowProvisioningUpdates
